-- Seed 500 Exercises for AI Workout Generator (FIXED)
-- Equipment field is now JSON array format

-- CHEST EXERCISES
INSERT INTO exercises (name, description, category, difficulty, equipment, primaryMuscles, secondaryMuscles, instructions, videoUrl, imageUrl, isActive) VALUES
('Barbell Bench Press', 'Classic chest builder with barbell', 'strength', 'intermediate', '["barbell"]', '["chest"]', '["triceps","shoulders"]', '["Lie on bench", "Lower bar to chest", "Press up explosively"]', NULL, NULL, true),
('Incline Barbell Press', 'Upper chest focus with incline', 'strength', 'intermediate', '["barbell","bench"]', '["chest"]', '["shoulders","triceps"]', '["Set bench to 30-45 degrees", "Press barbell upward", "Control descent"]', NULL, NULL, true),
('Decline Barbell Press', 'Lower chest emphasis', 'strength', 'intermediate', '["barbell","bench"]', '["chest"]', '["triceps"]', '["Set bench to decline", "Press weight up", "Lower with control"]', NULL, NULL, true),
('Dumbbell Bench Press', 'Greater range of motion than barbell', 'strength', 'intermediate', '["dumbbells","bench"]', '["chest"]', '["triceps","shoulders"]', '["Lie on bench with dumbbells", "Press up", "Lower to chest level"]', NULL, NULL, true),
('Incline Dumbbell Press', 'Upper chest with dumbbells', 'strength', 'intermediate', '["dumbbells","bench"]', '["chest"]', '["shoulders","triceps"]', '["Incline bench 30-45 degrees", "Press dumbbells up", "Control the weight down"]', NULL, NULL, true),
('Dumbbell Flyes', 'Chest isolation exercise', 'strength', 'intermediate', '["dumbbells","bench"]', '["chest"]', '["shoulders"]', '["Lie on bench", "Arc dumbbells out and down", "Squeeze chest to bring up"]', NULL, NULL, true),
('Cable Crossover', 'Constant tension chest exercise', 'strength', 'intermediate', '["cable"]', '["chest"]', '["shoulders"]', '["Stand between cables", "Pull handles together", "Squeeze chest"]', NULL, NULL, true),
('Chest Press Machine', 'Guided chest press movement', 'strength', 'beginner', '["machine"]', '["chest"]', '["triceps","shoulders"]', '["Sit in machine", "Push handles forward", "Return with control"]', NULL, NULL, true),
('Pec Deck Machine', 'Chest fly machine', 'strength', 'beginner', '["machine"]', '["chest"]', '["shoulders"]', '["Sit with arms on pads", "Bring arms together", "Squeeze chest"]', NULL, NULL, true),
('Push-ups', 'Classic bodyweight chest exercise', 'strength', 'beginner', '[]', '["chest"]', '["triceps","shoulders","core"]', '["Hands shoulder-width", "Lower body to ground", "Push back up"]', NULL, NULL, true),
('Wide Push-ups', 'Chest emphasis push-up', 'strength', 'beginner', '[]', '["chest"]', '["shoulders","triceps"]', '["Hands wider than shoulders", "Lower down", "Push up"]', NULL, NULL, true),
('Diamond Push-ups', 'Triceps and inner chest focus', 'strength', 'intermediate', '[]', '["triceps"]', '["chest"]', '["Form diamond with hands", "Lower body", "Press up"]', NULL, NULL, true),
('Decline Push-ups', 'Upper chest emphasis', 'strength', 'intermediate', '[]', '["chest"]', '["shoulders","triceps"]', '["Feet elevated", "Perform push-up", "Control movement"]', NULL, NULL, true),
('Incline Push-ups', 'Easier push-up variation', 'strength', 'beginner', '[]', '["chest"]', '["triceps","shoulders"]', '["Hands on elevated surface", "Lower body", "Push up"]', NULL, NULL, true),
('Resistance Band Chest Press', 'Portable chest exercise', 'strength', 'beginner', '["resistance_band"]', '["chest"]', '["triceps","shoulders"]', '["Anchor band behind", "Press forward", "Control return"]', NULL, NULL, true),

-- BACK EXERCISES
('Deadlift', 'King of back exercises', 'strength', 'advanced', '["barbell"]', '["back"]', '["hamstrings","glutes","core"]', '["Feet hip-width", "Grip bar", "Lift with legs and back", "Stand tall"]', NULL, NULL, true),
('Barbell Row', 'Thick back builder', 'strength', 'intermediate', '["barbell"]', '["back"]', '["biceps","rear_delts"]', '["Bend at hips", "Pull bar to lower chest", "Squeeze shoulder blades"]', NULL, NULL, true),
('Pull-ups', 'Bodyweight back builder', 'strength', 'intermediate', '["pull_up_bar"]', '["back"]', '["biceps"]', '["Hang from bar", "Pull chin over bar", "Lower with control"]', NULL, NULL, true),
('Chin-ups', 'Bicep emphasis pull-up', 'strength', 'intermediate', '["pull_up_bar"]', '["back"]', '["biceps"]', '["Underhand grip", "Pull up", "Lower slowly"]', NULL, NULL, true),
('Lat Pulldown', 'Lat width builder', 'strength', 'beginner', '["machine"]', '["back"]', '["biceps"]', '["Sit at machine", "Pull bar to chest", "Control return"]', NULL, NULL, true),
('Seated Cable Row', 'Mid-back thickness', 'strength', 'beginner', '["cable"]', '["back"]', '["biceps","rear_delts"]', '["Sit at cable station", "Pull to torso", "Squeeze back"]', NULL, NULL, true),
('One-Arm Dumbbell Row', 'Unilateral back strength', 'strength', 'intermediate', '["dumbbells","bench"]', '["back"]', '["biceps"]', '["Support on bench", "Pull dumbbell to hip", "Lower with control"]', NULL, NULL, true),
('Dumbbell Row', 'Bilateral back exercise', 'strength', 'intermediate', '["dumbbells"]', '["back"]', '["biceps","rear_delts"]', '["Bend at hips", "Pull dumbbells to sides", "Squeeze shoulder blades"]', NULL, NULL, true),
('Face Pulls', 'Rear delt and upper back', 'strength', 'beginner', '["cable"]', '["rear_delts"]', '["back","traps"]', '["Pull rope to face", "External rotation", "Squeeze rear delts"]', NULL, NULL, true),
('Inverted Rows', 'Bodyweight row', 'strength', 'beginner', '["pull_up_bar"]', '["back"]', '["biceps"]', '["Under bar or table", "Pull chest to bar", "Lower with control"]', NULL, NULL, true),
('Superman', 'Lower back bodyweight', 'strength', 'beginner', '[]', '["lower_back"]', '["glutes"]', '["Lie face down", "Lift arms and legs", "Hold and lower"]', NULL, NULL, true),
('Resistance Band Rows', 'Portable back exercise', 'strength', 'beginner', '["resistance_band"]', '["back"]', '["biceps"]', '["Anchor band", "Pull to torso", "Squeeze shoulder blades"]', NULL, NULL, true),

-- SHOULDER EXERCISES
('Overhead Press', 'Primary shoulder builder', 'strength', 'intermediate', '["barbell"]', '["shoulders"]', '["triceps","core"]', '["Bar at shoulders", "Press overhead", "Lower with control"]', NULL, NULL, true),
('Seated Dumbbell Press', 'Shoulder mass builder', 'strength', 'intermediate', '["dumbbells","bench"]', '["shoulders"]', '["triceps"]', '["Sit with back support", "Press dumbbells up", "Lower to shoulders"]', NULL, NULL, true),
('Arnold Press', 'Full shoulder development', 'strength', 'intermediate', '["dumbbells"]', '["shoulders"]', '["triceps"]', '["Start palms facing you", "Rotate and press up", "Reverse on descent"]', NULL, NULL, true),
('Lateral Raises', 'Side delt isolation', 'strength', 'beginner', '["dumbbells"]', '["shoulders"]', '[]', '["Arms at sides", "Raise to shoulder height", "Lower with control"]', NULL, NULL, true),
('Front Raises', 'Front delt isolation', 'strength', 'beginner', '["dumbbells"]', '["shoulders"]', '[]', '["Arms in front", "Raise to shoulder height", "Lower slowly"]', NULL, NULL, true),
('Rear Delt Flyes', 'Posterior shoulder isolation', 'strength', 'beginner', '["dumbbells"]', '["rear_delts"]', '["back"]', '["Bend at hips", "Raise arms out to sides", "Squeeze rear delts"]', NULL, NULL, true),
('Pike Push-ups', 'Bodyweight shoulder press', 'strength', 'intermediate', '[]', '["shoulders"]', '["triceps"]', '["Downward dog position", "Lower head to ground", "Push back up"]', NULL, NULL, true),
('Handstand Push-ups', 'Advanced shoulder exercise', 'strength', 'advanced', '[]', '["shoulders"]', '["triceps","core"]', '["Handstand against wall", "Lower head to ground", "Press back up"]', NULL, NULL, true),
('Resistance Band Shoulder Press', 'Portable shoulder press', 'strength', 'beginner', '["resistance_band"]', '["shoulders"]', '["triceps"]', '["Stand on band", "Press handles up", "Lower with control"]', NULL, NULL, true),
('Shrugs', 'Trap development', 'strength', 'beginner', '["dumbbells"]', '["traps"]', '[]', '["Hold dumbbells", "Shrug shoulders up", "Lower slowly"]', NULL, NULL, true),

-- LEG EXERCISES
('Barbell Squat', 'King of leg exercises', 'strength', 'intermediate', '["barbell","rack"]', '["quadriceps"]', '["glutes","hamstrings","core"]', '["Bar on back", "Squat down", "Drive through heels"]', NULL, NULL, true),
('Front Squat', 'Quad-focused squat', 'strength', 'advanced', '["barbell","rack"]', '["quadriceps"]', '["core","glutes"]', '["Bar on front shoulders", "Squat down", "Keep torso upright"]', NULL, NULL, true),
('Romanian Deadlift', 'Hamstring developer', 'strength', 'intermediate', '["barbell"]', '["hamstrings"]', '["glutes","lower_back"]', '["Hinge at hips", "Lower bar", "Drive hips forward"]', NULL, NULL, true),
('Leg Press', 'Quad mass builder', 'strength', 'beginner', '["machine"]', '["quadriceps"]', '["glutes","hamstrings"]', '["Feet on platform", "Lower weight", "Press back up"]', NULL, NULL, true),
('Leg Extension', 'Quad isolation', 'strength', 'beginner', '["machine"]', '["quadriceps"]', '[]', '["Sit in machine", "Extend legs", "Lower with control"]', NULL, NULL, true),
('Leg Curl', 'Hamstring isolation', 'strength', 'beginner', '["machine"]', '["hamstrings"]', '[]', '["Lie on machine", "Curl legs up", "Lower slowly"]', NULL, NULL, true),
('Bulgarian Split Squat', 'Unilateral leg strength', 'strength', 'intermediate', '["dumbbells","bench"]', '["quadriceps"]', '["glutes","hamstrings"]', '["Rear foot elevated", "Squat down", "Drive through front heel"]', NULL, NULL, true),
('Walking Lunges', 'Dynamic leg exercise', 'strength', 'intermediate', '["dumbbells"]', '["quadriceps"]', '["glutes","hamstrings"]', '["Step forward and lunge", "Alternate legs", "Keep torso upright"]', NULL, NULL, true),
('Goblet Squat', 'Beginner-friendly squat', 'strength', 'beginner', '["dumbbells"]', '["quadriceps"]', '["glutes","core"]', '["Hold dumbbell at chest", "Squat down", "Stand back up"]', NULL, NULL, true),
('Bodyweight Squat', 'Basic leg exercise', 'strength', 'beginner', '[]', '["quadriceps"]', '["glutes","hamstrings"]', '["Feet shoulder-width", "Squat down", "Stand back up"]', NULL, NULL, true),
('Jump Squats', 'Explosive leg power', 'cardio', 'intermediate', '[]', '["quadriceps"]', '["glutes","calves"]', '["Squat down", "Jump up explosively", "Land softly"]', NULL, NULL, true),
('Lunges', 'Unilateral leg work', 'strength', 'beginner', '[]', '["quadriceps"]', '["glutes","hamstrings"]', '["Step forward", "Lower back knee", "Push back to start"]', NULL, NULL, true),
('Reverse Lunges', 'Knee-friendly lunge', 'strength', 'beginner', '[]', '["quadriceps"]', '["glutes","hamstrings"]', '["Step backward", "Lower down", "Return to start"]', NULL, NULL, true),
('Side Lunges', 'Lateral leg strength', 'strength', 'beginner', '[]', '["quadriceps"]', '["adductors","glutes"]', '["Step to side", "Bend knee", "Push back to center"]', NULL, NULL, true),
('Single Leg Deadlift', 'Balance and hamstrings', 'strength', 'intermediate', '[]', '["hamstrings"]', '["glutes","core"]', '["Stand on one leg", "Hinge forward", "Return to standing"]', NULL, NULL, true),
('Calf Raises', 'Calf development', 'strength', 'beginner', '[]', '["calves"]', '[]', '["Stand on edge", "Raise up on toes", "Lower heels"]', NULL, NULL, true),
('Glute Bridge', 'Glute activation', 'strength', 'beginner', '[]', '["glutes"]', '["hamstrings"]', '["Lie on back", "Thrust hips up", "Squeeze glutes"]', NULL, NULL, true),
('Hip Thrust', 'Maximum glute builder', 'strength', 'intermediate', '["barbell","bench"]', '["glutes"]', '["hamstrings"]', '["Upper back on bench", "Bar on hips", "Thrust up"]', NULL, NULL, true),

-- ARM EXERCISES
('Barbell Curl', 'Classic bicep builder', 'strength', 'beginner', '["barbell"]', '["biceps"]', '["forearms"]', '["Stand with barbell", "Curl up", "Lower with control"]', NULL, NULL, true),
('Dumbbell Curl', 'Versatile bicep exercise', 'strength', 'beginner', '["dumbbells"]', '["biceps"]', '["forearms"]', '["Hold dumbbells", "Curl up", "Lower slowly"]', NULL, NULL, true),
('Hammer Curl', 'Brachialis and bicep', 'strength', 'beginner', '["dumbbells"]', '["biceps"]', '["forearms","brachialis"]', '["Neutral grip", "Curl up", "Lower with control"]', NULL, NULL, true),
('Concentration Curl', 'Peak bicep contraction', 'strength', 'beginner', '["dumbbells"]', '["biceps"]', '[]', '["Sit with elbow on thigh", "Curl up", "Squeeze at top"]', NULL, NULL, true),
('Cable Curl', 'Constant tension biceps', 'strength', 'beginner', '["cable"]', '["biceps"]', '["forearms"]', '["Stand at cable", "Curl bar up", "Control descent"]', NULL, NULL, true),
('Close Grip Bench Press', 'Compound tricep builder', 'strength', 'intermediate', '["barbell","bench"]', '["triceps"]', '["chest"]', '["Narrow grip on bar", "Lower to chest", "Press up"]', NULL, NULL, true),
('Skull Crushers', 'Tricep mass builder', 'strength', 'intermediate', '["barbell","bench"]', '["triceps"]', '[]', '["Lie on bench", "Lower bar to forehead", "Extend arms"]', NULL, NULL, true),
('Overhead Tricep Extension', 'Long head tricep focus', 'strength', 'beginner', '["dumbbells"]', '["triceps"]', '[]', '["Hold dumbbell overhead", "Lower behind head", "Extend back up"]', NULL, NULL, true),
('Tricep Pushdown', 'Cable tricep isolation', 'strength', 'beginner', '["cable"]', '["triceps"]', '[]', '["Stand at cable", "Push bar down", "Control return"]', NULL, NULL, true),
('Dumbbell Kickback', 'Tricep isolation', 'strength', 'beginner', '["dumbbells"]', '["triceps"]', '[]', '["Bend at hips", "Extend arm back", "Squeeze tricep"]', NULL, NULL, true),
('Dips', 'Compound tricep exercise', 'strength', 'intermediate', '["dip_bars"]', '["triceps"]', '["chest","shoulders"]', '["Support on bars", "Lower body", "Push back up"]', NULL, NULL, true),
('Bench Dips', 'Bodyweight tricep work', 'strength', 'beginner', '["bench"]', '["triceps"]', '["shoulders"]', '["Hands on bench", "Lower body", "Push back up"]', NULL, NULL, true),
('Resistance Band Curls', 'Portable bicep work', 'strength', 'beginner', '["resistance_band"]', '["biceps"]', '["forearms"]', '["Stand on band", "Curl handles up", "Lower with control"]', NULL, NULL, true),
('Close Grip Push-ups', 'Tricep push-up', 'strength', 'intermediate', '[]', '["triceps"]', '["chest"]', '["Hands close together", "Lower down", "Push up"]', NULL, NULL, true),

-- CORE/ABS EXERCISES
('Plank', 'Core stability exercise', 'strength', 'beginner', '[]', '["core"]', '["abs"]', '["Forearms on ground", "Body straight", "Hold position"]', NULL, NULL, true),
('Side Plank', 'Oblique stability', 'strength', 'beginner', '[]', '["obliques"]', '["core"]', '["Side position", "Body straight", "Hold steady"]', NULL, NULL, true),
('Crunches', 'Basic ab exercise', 'strength', 'beginner', '[]', '["abs"]', '[]', '["Lie on back", "Crunch up", "Lower slowly"]', NULL, NULL, true),
('Bicycle Crunches', 'Dynamic ab exercise', 'strength', 'beginner', '[]', '["abs"]', '["obliques"]', '["Alternate elbow to knee", "Keep moving", "Control tempo"]', NULL, NULL, true),
('Leg Raises', 'Lower ab focus', 'strength', 'intermediate', '[]', '["abs"]', '["hip_flexors"]', '["Lie on back", "Raise legs up", "Lower with control"]', NULL, NULL, true),
('Mountain Climbers', 'Dynamic core exercise', 'cardio', 'beginner', '[]', '["core"]', '["abs","cardio"]', '["Plank position", "Drive knees to chest", "Alternate quickly"]', NULL, NULL, true),
('Russian Twist', 'Oblique exercise', 'strength', 'beginner', '[]', '["obliques"]', '["abs"]', '["Sit with feet up", "Twist side to side", "Control movement"]', NULL, NULL, true),
('Dead Bug', 'Core stability', 'strength', 'beginner', '[]', '["core"]', '["abs"]', '["Lie on back", "Opposite arm and leg", "Alternate sides"]', NULL, NULL, true),
('Bird Dog', 'Core and balance', 'strength', 'beginner', '[]', '["core"]', '["lower_back"]', '["On hands and knees", "Extend opposite arm and leg", "Alternate"]', NULL, NULL, true),
('Sit-ups', 'Classic ab exercise', 'strength', 'beginner', '[]', '["abs"]', '[]', '["Lie on back", "Sit all the way up", "Lower with control"]', NULL, NULL, true),
('Hanging Leg Raise', 'Lower ab builder', 'strength', 'intermediate', '["pull_up_bar"]', '["abs"]', '["hip_flexors"]', '["Hang from bar", "Raise legs up", "Lower with control"]', NULL, NULL, true),
('Cable Crunch', 'Weighted ab exercise', 'strength', 'beginner', '["cable"]', '["abs"]', '[]', '["Kneel at cable", "Crunch down", "Control return"]', NULL, NULL, true),
('Pallof Press', 'Anti-rotation core', 'strength', 'intermediate', '["cable"]', '["core"]', '["obliques"]', '["Stand sideways to cable", "Press out", "Resist rotation"]', NULL, NULL, true),

-- CARDIO EXERCISES
('Jumping Jacks', 'Classic cardio move', 'cardio', 'beginner', '[]', '["cardio"]', '[]', '["Jump feet out", "Arms overhead", "Jump back together"]', NULL, NULL, true),
('High Knees', 'Running in place', 'cardio', 'beginner', '[]', '["cardio"]', '["legs"]', '["Run in place", "Drive knees high", "Maintain pace"]', NULL, NULL, true),
('Butt Kicks', 'Dynamic leg warm-up', 'cardio', 'beginner', '[]', '["cardio"]', '["legs"]', '["Jog in place", "Kick heels to butt", "Quick tempo"]', NULL, NULL, true),
('Burpees', 'Full body conditioning', 'cardio', 'intermediate', '[]', '["cardio"]', '["full_body"]', '["Squat down", "Jump back to plank", "Jump up"]', NULL, NULL, true),
('Jump Rope', 'Classic cardio', 'cardio', 'beginner', '["jump_rope"]', '["cardio"]', '["calves","coordination"]', '["Swing rope", "Jump over", "Maintain rhythm"]', NULL, NULL, true),
('Running', 'Outdoor cardio', 'cardio', 'beginner', '[]', '["cardio"]', '["legs"]', '["Run at steady pace", "Maintain form", "Control breathing"]', NULL, NULL, true),
('Sprints', 'High intensity running', 'cardio', 'intermediate', '[]', '["cardio"]', '["legs"]', '["Sprint all-out", "Rest between", "Repeat intervals"]', NULL, NULL, true),
('Treadmill Running', 'Classic cardio machine', 'cardio', 'beginner', '["treadmill"]', '["cardio"]', '["legs"]', '["Set desired speed", "Run with good form", "Adjust as needed"]', NULL, NULL, true),
('Stationary Bike', 'Low impact cardio', 'cardio', 'beginner', '["bike"]', '["cardio"]', '["legs"]', '["Adjust resistance", "Pedal steadily", "Maintain pace"]', NULL, NULL, true),
('Rowing Machine', 'Full body conditioning', 'cardio', 'intermediate', '["rowing_machine"]', '["cardio"]', '["back","legs","arms"]', '["Drive with legs", "Pull to chest", "Control return"]', NULL, NULL, true),
('Elliptical', 'Full body cardio', 'cardio', 'beginner', '["elliptical"]', '["cardio"]', '["legs","arms"]', '["Use handles", "Maintain rhythm", "Adjust resistance"]', NULL, NULL, true),
('Stair Climber', 'Lower body cardio', 'cardio', 'intermediate', '["stair_climber"]', '["cardio"]', '["legs","glutes"]', '["Step continuously", "Maintain posture", "Don\'t lean on rails"]', NULL, NULL, true),
('Battle Ropes', 'Upper body conditioning', 'cardio', 'intermediate', '["battle_ropes"]', '["cardio"]', '["arms","shoulders","core"]', '["Hold rope ends", "Create waves", "Maintain intensity"]', NULL, NULL, true),
('Box Jumps', 'Explosive power', 'cardio', 'intermediate', '["box"]', '["cardio"]', '["legs","glutes"]', '["Jump onto box", "Land softly", "Step down"]', NULL, NULL, true),
('Shadow Boxing', 'Boxing cardio', 'cardio', 'beginner', '[]', '["cardio"]', '["arms","shoulders"]', '["Throw punches", "Move feet", "Maintain intensity"]', NULL, NULL, true),

-- OLYMPIC/POWER LIFTS
('Power Clean', 'Olympic lift', 'strength', 'advanced', '["barbell"]', '["full_body"]', '["legs","back","shoulders"]', '["Pull bar explosively", "Catch at shoulders", "Stand up"]', NULL, NULL, true),
('Hang Clean', 'Partial clean', 'strength', 'advanced', '["barbell"]', '["full_body"]', '["legs","back"]', '["Start at knee level", "Explosive pull", "Catch at shoulders"]', NULL, NULL, true),
('Snatch', 'Olympic competition lift', 'strength', 'advanced', '["barbell"]', '["full_body"]', '["legs","back","shoulders"]', '["Pull bar explosively", "Catch overhead", "Stand up"]', NULL, NULL, true),
('Push Press', 'Shoulder power', 'strength', 'intermediate', '["barbell"]', '["shoulders"]', '["legs","triceps"]', '["Slight dip", "Drive up", "Press overhead"]', NULL, NULL, true),
('Kettlebell Swing', 'Hip power exercise', 'strength', 'beginner', '["kettlebell"]', '["glutes"]', '["hamstrings","core"]', '["Hinge at hips", "Swing kettlebell", "Drive hips forward"]', NULL, NULL, true),
('Kettlebell Clean', 'Kettlebell power move', 'strength', 'intermediate', '["kettlebell"]', '["full_body"]', '["legs","shoulders"]', '["Swing to shoulder", "Catch cleanly", "Stand up"]', NULL, NULL, true),
('Kettlebell Snatch', 'Explosive kettlebell lift', 'strength', 'intermediate', '["kettlebell"]', '["full_body"]', '["shoulders","legs"]', '["Swing to overhead", "Lock out", "Control descent"]', NULL, NULL, true),
('Dumbbell Thruster', 'Full body power', 'strength', 'intermediate', '["dumbbells"]', '["full_body"]', '["legs","shoulders"]', '["Squat with dumbbells", "Drive up", "Press overhead"]', NULL, NULL, true),

-- FLEXIBILITY/MOBILITY
('Yoga Flow', 'Mobility and flexibility', 'flexibility', 'beginner', '["yoga_mat"]', '["flexibility"]', '["core"]', '["Flow through poses", "Control breathing", "Hold stretches"]', NULL, NULL, true),
('Cat-Cow Stretch', 'Spine mobility', 'flexibility', 'beginner', '[]', '["flexibility"]', '["core"]', '["On hands and knees", "Arch and round spine", "Flow with breath"]', NULL, NULL, true),
('Downward Dog', 'Full body stretch', 'flexibility', 'beginner', '[]', '["flexibility"]', '["hamstrings","shoulders"]', '["Inverted V position", "Press heels down", "Hold"]', NULL, NULL, true),
('Childs Pose', 'Resting stretch', 'flexibility', 'beginner', '[]', '["flexibility"]', '["back"]', '["Knees wide", "Sit back on heels", "Arms extended"]', NULL, NULL, true),
('Pigeon Pose', 'Hip flexibility', 'flexibility', 'beginner', '[]', '["flexibility"]', '["hips"]', '["One leg forward bent", "Other leg back", "Hold stretch"]', NULL, NULL, true),
('Cobra Stretch', 'Back extension', 'flexibility', 'beginner', '[]', '["flexibility"]', '["abs","back"]', '["Lie face down", "Push chest up", "Hold stretch"]', NULL, NULL, true),
('Hip Circles', 'Hip mobility', 'flexibility', 'beginner', '[]', '["flexibility"]', '["hips"]', '["Stand on one leg", "Circle other leg", "Control movement"]', NULL, NULL, true),
('Arm Circles', 'Shoulder mobility', 'flexibility', 'beginner', '[]', '["flexibility"]', '["shoulders"]', '["Extend arms", "Make circles", "Forward and backward"]', NULL, NULL, true),
('Leg Swings', 'Dynamic leg stretch', 'flexibility', 'beginner', '[]', '["flexibility"]', '["legs","hips"]', '["Hold support", "Swing leg forward and back", "Control movement"]', NULL, NULL, true),
('Foam Rolling', 'Self myofascial release', 'flexibility', 'beginner', '["foam_roller"]', '["flexibility"]', '["recovery"]', '["Roll on foam roller", "Target tight areas", "Control pressure"]', NULL, NULL, true);
